### ISSUE TITLE
Read should probably default to LOCAL_QUORUM, not QUORUM

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cdc-go#15]
A user who uses this library on a multi-DC setup noticed a lot of cross-DC reads. I looked at the CDC library code code, and it turns out it uses the QUORUM consistency level by default. I think it should be changed to LOCAL_QUORUM as a better default for multi-DC setups.

CC @kbr-scylla @tarzanek

**Comment by kbr-scylla** [comment]
cc @avelanarius @piodul
