### ISSUE TITLE
Extreme delays for simple consumer

### ISSUE THREAD

**Issue by danthegoodman1** [scylladb/scylla-cdc-go#7]
Using the simple consumer of:

```go
package main
​
import (
	"context"
	"fmt"
	"log"
	"os"
​
	"github.com/gocql/gocql"
	scyllacdc "github.com/scylladb/scylla-cdc-go"
)
​
// Make sure you create the following table before you run this example:
// CREATE TABLE ks.tbl (pk int, ck int, v int, PRIMARY KEY (pk, ck)) WITH cdc = {'enabled': 'true'};
​
func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.DCAwareRoundRobinPolicy("local-dc"))
	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}
	defer session.Close()
​
	cfg := &scyllacdc.ReaderConfig{
		Session:               session,
		TableNames:            []string{"identity_ksp.identities"},
		ChangeConsumerFactory: changeConsumerFactory,
		Logger:                log.New(os.Stderr, "", log.Ldate|log.Lshortfile),
	}
​
	reader, err := scyllacdc.NewReader(context.Background(), cfg)
	if err != nil {
		log.Fatal(err)
	}
​
	if err := reader.Run(context.Background()); err != nil {
		log.Fatal(err)
	}
}
​
func consumeChange(ctx context.Context, tableName string, c scyllacdc.Change) error {
	for _, changeRow := range c.Delta {
		pkRaw, _ := changeRow.GetValue("namespace")
		ckRaw, _ := changeRow.GetValue("id")
​
		pk := pkRaw.(*string)
		ck := ckRaw.(*string)
​
		fmt.Printf("Operation: %s, pk: %s, ck: %s\n", changeRow.GetOperation(),
			*pk, *ck)
	}
​
	return nil
}
​
func nullableIntToStr(i *int) string {
	if i == nil {
		return "null"
	}
	return fmt.Sprintf("%d", *i)
}
​
var changeConsumerFactory = scyllacdc.MakeChangeConsumerFactoryFromFunc(consumeChange)
```

I don't see changes in my cdc table for tens of seconds. I tried adding in an advanced config with low durations:

```go
Advanced: scyllacdc.AdvancedReaderConfig{
			PostEmptyQueryDelay:    time.Millisecond * 1,
			PostNonEmptyQueryDelay: time.Millisecond * 1,
			ConfidenceWindowSize:   time.Second * 1,
			PostFailedQueryDelay:   time.Millisecond * 1,
			QueryTimeWindowSize:    time.Second * 1,
			ChangeAgeLimit:         time.Second * 100,
		},
```

Some starting logs:
```
2021/11/18 reader.go:189: no saved progress found, will start reading from 2021-11-18 18:08:53.865218 -0500 EST m=-99.985517751
2021/11/18 topology.go:136: starting generation fetcher loop
2021/11/18 topology.go:272: pushing generation 2021-09-25 22:34:51.862 +0000 UTC
2021/11/18 reader.go:242: starting reading generation 2021-09-25 22:34:51.862 +0000 UTC from timestamp 2021-11-18 18:08:53.865218 -0500 EST m=-99.985517751
2021/11/18 reader.go:251: grouped 1536 streams into 256 batches
```

And I got somewhat acceptible performance (7-10 seconds after insert), but the CPU on scylla was high.

I can confirm that the records in the CDC table are available immediatelly after insert, so I am wondering what can be done to make this package more snappy with it's consumption of CDC changes, or if anyone have been experiencing the same?

**Comment by piodul** [comment]
@danthegoodman1  Let me give some suggestions with respect to the choice of the advanced parameters - please try them out and see if they help.

First, try setting `PostXYZQueryDelay` parameters to larger values. They have the biggest influence on the number of queries the library sends per second, and decreasing it will most likely reduce your CPU load on the Scylla side. One millisecond is a __very__ low choice for this parameter and the intensity of queries may be a bit much if you are testing locally on a laptop. I saw on the ScyllaDB-Users Slack that you would like the changes to be processed within seconds, and you already set the `ConfidenceWindowSize` to one second, so how about setting `PostXYZQueryDelay`s to values from range `[200ms, 1s]`? The resulting latency should be in range of `[ConfidenceWindowSize, ConfidenceWindowSize + PostXYZQueryDelay]`.

Second, take note of the `ChangeAgeLimit` parameter. When you start the library it starts reading from `now - ChangeAgeLimit`, so it needs to perform several reads before it catches up to the present. Depending on the `ChangeAgeLimit`, the latency might be poor at the beginning but should gradually improve over time. If you are not interested in replaying the old changes and are just testing the latency, you may as well reduce the `ChangeAgeLimit`.

**Comment by danthegoodman1** [comment]
@piodul thanks, I will give those a try and report back.

I also need to configure out a solution for multiple consumers, I think I’ll need a lock table using LWTs for that if this is the route I tackle

**Comment by danthegoodman1** [comment]
```go
cfg := &scyllacdc.ReaderConfig{
		Session:               session,
		TableNames:            []string{"identity_ksp.identities"},
		ChangeConsumerFactory: changeConsumerFactory,
		Logger:                log.New(os.Stderr, "", log.Ldate|log.Lshortfile),
		Advanced: scyllacdc.AdvancedReaderConfig{
			PostEmptyQueryDelay:    time.Millisecond * 500,
			PostNonEmptyQueryDelay: time.Millisecond * 500,
			PostFailedQueryDelay:   time.Millisecond * 500,
			ConfidenceWindowSize:   time.Second * 1,
			QueryTimeWindowSize:    time.Second * 10,
			ChangeAgeLimit:         time.Second * 10,
		},
	}
```

With these settings I am getting much better performance, thanks!
